### ISSUE TITLE
HTTP Status 404 - /WebGoat/attack

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kipyegonmark/webgoat#23]
```
What steps will reproduce the problem?
1. ./webgoat.sh start8080

What is the expected output? What do you see instead?

# ./webgoat.sh start8080
Using CATALINA_BASE:   ./tomcat
Using CATALINA_HOME:   ./tomcat
Using CATALINA_TMPDIR: ./tomcat/temp
Using JAVA_HOME:       /usr/lib/jvm/java-1.5.0-sun/

  Open http://127.0.0.1:8080/WebGoat/attack
  Username: guest
  Password: guest
  Or try http://guest:guest@127.0.0.1:8080/WebGoat/attack 

    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:312)
    at
org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.ja
va:119)
    at org.apache.catalina.core.ContainerBase.stop(ContainerBase.java:1043)
    at org.apache.catalina.core.ContainerBase.stop(ContainerBase.java:1055)
    at org.apache.catalina.core.StandardEngine.stop(StandardEngine.java:442)
    at org.apache.catalina.core.StandardService.stop(StandardService.java:512)
    at org.apache.catalina.core.StandardServer.stop(StandardServer.java:2044)
    at org.apache.catalina.startup.Catalina.stop(Catalina.java:586)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:561)
    ... 6 more
10-gen-2009 23.35.36 org.apache.coyote.http11.Http11Protocol init
INFO: Initializing Coyote HTTP/1.1 on http-127.0.0.1-8080
10-gen-2009 23.35.38 org.apache.coyote.http11.Http11Protocol init
INFO: Initializing Coyote HTTP/1.1 on http-127.0.0.1-8443
10-gen-2009 23.35.38 org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 2666 ms
10-gen-2009 23.35.38 org.apache.catalina.core.StandardService start
INFO: Starting service Catalina
10-gen-2009 23.35.38 org.apache.catalina.core.StandardEngine start
INFO: Starting Servlet Engine: Apache Tomcat/5.5.4
10-gen-2009 23.35.38 org.apache.catalina.core.StandardHost start
INFO: XML validation disabled
10-gen-2009 23.35.38 org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive WebGoat.war
10-gen-2009 23.35.39 org.apache.catalina.startup.HostConfig deployWAR
GRAVE: Error deploying web application archive WebGoat.war
java.lang.UnsupportedClassVersionError: Bad version number in .class file
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
    at
org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader
.java:1626)
    at
org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:85
0)
    at
org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:12
99)
    at
org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:11
81)
    at
org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:988)
    at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:886)
    at
org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:3817
)
    at org.apache.catalina.core.StandardContext.start(StandardContext.java:4079)
    at
org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:755)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:739)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:525)
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:777)
    at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:672)
    at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:472)
    at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1079)
    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:310)
    at
org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.ja
va:119)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1011)
    at org.apache.catalina.core.StandardHost.start(StandardHost.java:718)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1003)
    at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:437)
    at org.apache.catalina.core.StandardService.start(StandardService.java:450)
    at org.apache.catalina.core.StandardServer.start(StandardServer.java:2010)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:537)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
    at java.lang.reflect.Method.invoke(Method.java:585)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:271)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:409)
10-gen-2009 23.35.39 org.apache.catalina.core.ApplicationContext log
INFO: org.apache.webapp.balancer.BalancerFilter: init(): ruleChain:
[org.apache.webapp.balancer.RuleChain:
[org.apache.webapp.balancer.rules.URLStringMatchRule: Target string: News /
Redirect URL: http://www.cnn.com],
[org.apache.webapp.balancer.rules.RequestParameterRule: Target param name:
paramName / Target param value: paramValue / Redirect URL:
http://www.yahoo.com],
[org.apache.webapp.balancer.rules.AcceptEverythingRule: Redirect URL:
http://jakarta.apache.org]]
10-gen-2009 23.35.39 org.apache.coyote.http11.Http11Protocol start
INFO: Starting Coyote HTTP/1.1 on http-127.0.0.1-8080
10-gen-2009 23.35.40 org.apache.coyote.http11.Http11Protocol start
INFO: Starting Coyote HTTP/1.1 on http-127.0.0.1-8443
- JK2: ajp13 listening on /127.0.0.1:8009
10-gen-2009 23.35.40 org.apache.jk.server.JkMain start
INFO: Jk running ID=0 time=0/23  config=null
10-gen-2009 23.35.40 org.apache.catalina.startup.Catalina start
INFO: Server startup in 2118 ms

What version of the product are you using? On what operating system?
WebGoat-5.2 on Ubuntu 8.04 LTS (i386) updated version.

Please provide any additional information below.


```

Original issue reported on code.google.com by `alfonso....@gmail.com` on 10 Jan 2009 at 10:41

**Comment by GoogleCodeExporter** [comment]
```
It looks like a JDK version problem.  

The error: 
   java.lang.UnsupportedClassVersionError: Bad version number in .class file
supports this.

While WebGoat is supposed to be built with 1.5.0, Based on the class files 
(bytes 6 &
7) in the release, WebGoat was built with J2SE 6.0

The java release delivered with WebGoat is: 1.6.0_01  You would need this 
version or
later in order to run WebGoat.



```

Original comment by `mayhe...@gmail.com` on 21 Jan 2009 at 4:15

**Comment by GoogleCodeExporter** [comment]
Original comment by `mayhe...@gmail.com` on 21 Jan 2009 at 4:16
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
Can you please help with configuration of Webgoat.

This is the error I got after running ./webgoat.sh start8080.I installed 
Webgoat 5.3 ,OpenJRE and Tomcat 5 on Backtrack.

Using CATALINA_BASE:   ./tomcat
Using CATALINA_HOME:   ./tomcat
Using CATALINA_TMPDIR: ./tomcat/temp
Using JRE_HOME:        /usr/lib/jvm/java-6-openjdk/bin/../
Using CLASSPATH:       ./tomcat/bin/bootstrap.jar

  Open http://127.0.0.1:8080/WebGoat/attack
  Username: guest
  Password: guest
  Or try http://guest:guest@127.0.0.1:8080/WebGoat/attack 

Jun 4, 2012 5:27:07 PM org.apache.coyote.http11.Http11BaseProtocol start
INFO: Starting Coyote HTTP/1.1 on http-127.0.0.1-8080
Jun 4, 2012 5:27:08 PM org.apache.jk.common.ChannelSocket init
INFO: JK: ajp13 listening on /0.0.0.0:8009
Jun 4, 2012 5:27:08 PM org.apache.jk.server.JkMain start
INFO: Jk running ID=0 time=0/392  config=null
Jun 4, 2012 5:27:08 PM org.apache.catalina.storeconfig.StoreLoader load
INFO: Find registry server-registry.xml at classpath resource
Jun 4, 2012 5:27:09 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 22954 ms
Jun 4, 2012 5:54:34 PM org.apache.catalina.core.AprLifecycleListener 
lifecycleEvent
INFO: The Apache Tomcat Native library which allows optimal performance in 
production environments was not found on the java.library.path: 
/usr/lib/jvm/java-6-openjdk/jre/lib/i386/client:/usr/lib/jvm/java-6-openjdk/jre/
lib/i386:/usr/lib/jvm/java-6-openjdk/jre/../lib/i386:/usr/java/packages/lib/i386
:/usr/lib/jni:/lib:/usr/lib
Jun 4, 2012 5:54:35 PM org.apache.coyote.http11.Http11BaseProtocol init
SEVERE: Error initializing endpoint
java.net.BindException: Address already in use:8080
    at org.apache.tomcat.util.net.PoolTcpEndpoint.initEndpoint(PoolTcpEndpoint.java:298)
    at org.apache.coyote.http11.Http11BaseProtocol.init(Http11BaseProtocol.java:139)
    at org.apache.catalina.connector.Connector.initialize(Connector.java:1017)
    at org.apache.catalina.core.StandardService.initialize(StandardService.java:578)
    at org.apache.catalina.core.StandardServer.initialize(StandardServer.java:782)
    at org.apache.catalina.startup.Catalina.load(Catalina.java:504)
    at org.apache.catalina.startup.Catalina.load(Catalina.java:524)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:267)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:432)
Jun 4, 2012 5:54:35 PM org.apache.catalina.startup.Catalina load
SEVERE: Catalina.start
LifecycleException:  Protocol handler initialization failed: 
java.net.BindException: Address already in use:8080
    at org.apache.catalina.connector.Connector.initialize(Connector.java:1019)
    at org.apache.catalina.core.StandardService.initialize(StandardService.java:578)
    at org.apache.catalina.core.StandardServer.initialize(StandardServer.java:782)
    at org.apache.catalina.startup.Catalina.load(Catalina.java:504)
    at org.apache.catalina.startup.Catalina.load(Catalina.java:524)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:267)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:432)
Jun 4, 2012 5:54:35 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 2225 ms
Jun 4, 2012 5:54:35 PM org.apache.catalina.core.StandardService start
INFO: Starting service Catalina
Jun 4, 2012 5:54:35 PM org.apache.catalina.core.StandardEngine start
INFO: Starting Servlet Engine: Apache Tomcat/5.5.28
Jun 4, 2012 5:54:35 PM org.apache.catalina.core.StandardHost start
INFO: XML validation disabled
Jun 4, 2012 5:54:37 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive webgoat.war
Jun 4, 2012 5:54:40 PM org.apache.coyote.http11.Http11BaseProtocol start
SEVERE: Error starting endpoint
java.net.BindException: Address already in use:8080
    at org.apache.tomcat.util.net.PoolTcpEndpoint.initEndpoint(PoolTcpEndpoint.java:298)
    at org.apache.tomcat.util.net.PoolTcpEndpoint.startEndpoint(PoolTcpEndpoint.java:313)
    at org.apache.coyote.http11.Http11BaseProtocol.start(Http11BaseProtocol.java:151)
    at org.apache.coyote.http11.Http11Protocol.start(Http11Protocol.java:76)
    at org.apache.catalina.connector.Connector.start(Connector.java:1090)
    at org.apache.catalina.core.StandardService.start(StandardService.java:457)
    at org.apache.catalina.core.StandardServer.start(StandardServer.java:700)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:552)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:295)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:433)
Jun 4, 2012 5:54:40 PM org.apache.catalina.startup.Catalina start
SEVERE: Catalina.start: 
LifecycleException:  service.getName(): "Catalina";  Protocol handler start 
failed: java.net.BindException: Address already in use:8080
    at org.apache.catalina.connector.Connector.start(Connector.java:1097)
    at org.apache.catalina.core.StandardService.start(StandardService.java:457)
    at org.apache.catalina.core.StandardServer.start(StandardServer.java:700)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:552)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:295)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:433)
Jun 4, 2012 5:54:40 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 5614 ms
Jun 4, 2012 5:54:40 PM org.apache.catalina.core.StandardServer await
SEVERE: StandardServer.await: create[8005]: 
java.net.BindException: Address already in use
    at java.net.PlainSocketImpl.socketBind(Native Method)
    at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:353)
    at java.net.ServerSocket.bind(ServerSocket.java:336)
    at java.net.ServerSocket.<init>(ServerSocket.java:202)
    at org.apache.catalina.core.StandardServer.await(StandardServer.java:363)
    at org.apache.catalina.startup.Catalina.await(Catalina.java:616)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:576)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:295)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:433)
Jun 4, 2012 5:54:40 PM org.apache.coyote.http11.Http11BaseProtocol pause
INFO: Pausing Coyote HTTP/1.1 on http-127.0.0.1-8080
Jun 4, 2012 5:54:41 PM org.apache.catalina.core.StandardService stop
INFO: Stopping service Catalina
Jun 4, 2012 5:54:42 PM org.apache.catalina.connector.MapperListener destroy
WARNING: Error unregistering MBeanServerDelegate
java.lang.NullPointerException
    at org.apache.catalina.connector.MapperListener.destroy(MapperListener.java:173)
    at org.apache.catalina.connector.Connector.stop(Connector.java:1138)
    at org.apache.catalina.core.StandardService.stop(StandardService.java:519)
    at org.apache.catalina.core.StandardServer.stop(StandardServer.java:734)
    at org.apache.catalina.startup.Catalina.stop(Catalina.java:602)
    at org.apache.catalina.startup.Catalina$CatalinaShutdownHook.run(Catalina.java:645)
Jun 4, 2012 5:54:42 PM org.apache.coyote.http11.Http11BaseProtocol destroy
INFO: Stopping Coyote HTTP/1.1 on http-127.0.0.1-8080
Jun 4, 2012 5:54:42 PM org.apache.catalina.connector.Connector stop
SEVERE: Coyote connector has not been started
Jun 4, 2012 5:54:42 PM org.apache.catalina.core.AprLifecycleListener 
lifecycleEvent
INFO: Failed shutdown of Apache Portable Runtime

```

Original comment by `abmsot...@googlemail.com` on 4 Jun 2012 at 5:04

**Comment by GoogleCodeExporter** [comment]
```
Hi All, running ./webgoat.sh start80 gives following messages:
using JRE_HOME /usr/lib/jvm/java-6-openjdk/jre/bin/java
open http:
username:
password:

eval 1: /usr/lib/jvm/java-6-openjdk/jre/bin/java/bin/java

From last line it is evident that bin/java is repeating, please someone helpe 
me on this issue.

Thanks
```

Original comment by `sa.naqv...@gmail.com` on 2 Oct 2012 at 5:31
